version: 2
jobs:
  dependencies:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          command: 'npm install -g karma'
      - run:
          command: 'npm install jasmine-core'
      - run:
          command: 'npm install karma-jasmine karma-junit-reporter karma-spec-reporter angular-mocks'
      - run:
          command: 'npm install -g karma-cli'
    # cache_directories:
    #   - ~/nvm
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - run:
          command: 'karma start'
workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - test:
          requires:
            - dependencies