version: 2
jobs:
  dependencies:
    pre:
    - npm install -g karma
    cache_directories:
      - ~/nvm
  test:
    override:
      - karma start
workflows:
  version: 2
  build_and_test:
    jobs:
      - test