version: 2
jobs:
  dependencies:
    steps:
      - run:
        command: 'npm install -g karma'
    # cache_directories:
    #   - ~/nvm
  test:
    steps:
      - run:
        command: 'karma start'
workflows:
  version: 2
  build_and_test:
    jobs:
      - test