version: 2
jobs:
  # dependencies:
  #   docker:
  #     - image: circleci/node:latest
  #   steps:
  #     - run:
  #         command: 'sudo npm install -g karma'
  #     - run:
  #         command: 'sudo npm install jasmine-core'
  #     - run:
  #         command: 'sudo npm install karma-jasmine karma-junit-reporter karma-spec-reporter angular-mocks'
  #     - run:
  #         command: 'sudo npm install -g karma-cli'
    # cache_directories:
    #   - ~/nvm
  test:
    working_directory: ~/angularjstictac
    docker:
      - image: circleci/node:latest
      # - image: selenium/standalone-chrome:latest
    steps:
      - checkout
      # - persist_to_workspace:
      #     root: ~/angularjstictac
      - run:
          command: 'sudo npm install -g karma'
      - run:
          command: 'sudo npm install jasmine-core'
      - run:
          command: 'sudo npm install -g karma-jasmine'
      - run:
          command: 'sudo npm install -g chrome-headless'
      - run:
          command: 'sudo npm install -g karma-chrome-launcher'
      - run:
          command: 'sudo npm install -g puppeteer --unsafe-perm=true'
      - run:
          command: 'sudo npm install karma-junit-reporter karma-spec-reporter angular-mocks'
      - run:
          command: 'sudo npm install -g karma-cli'
      - run:
          command: 'pwd'
      - run:
          command: 'ls'
      - run:
          # command: 'karma start karma.conf.js'
          command: 'CHROME_BIN=/usr/bin/google-chrome karma start karma.conf.js'
          # command: './node_modules/karma/bin/karma start'
          # command: '/usr/local/lib/node_modules/karma-cli/bin/karma start'
          # command: '/usr/local/bin/karma start'
workflows:
  version: 2
  build_and_test:
    jobs:
      # - dependencies
      - test
      # - test:
          # requires:
          #   - dependencies